export const conditionMap = {
    'Clear sky': 'sunny',
    'Mainly clear': 'sunny',
    'Partly cloudy': 'party_cloudy',
    'Overcast': 'overcast',
    'Fog': 'fog',
    'Depositing rime fog': 'fog',
    'Drizzle: Light': 'drizzle',
    'Drizzle: Moderate': 'drizzle',
    'Drizzle: Dense': 'drizzle',
    'Rain: Slight': 'rain',
    'Rain: Moderate': 'rain',
    'Rain: Heavy': 'rain',
    'Freezing Rain: Light': 'rain',
    'Freezing Rain: Heavy': 'rain',
    'Snow fall: Slight': 'snow',
    'Snow fall: Moderate': 'snow',
    'Snow fall: Heavy': 'snow',
    'Snow grains': 'snow',
    'Rain showers: Slight': 'rain',
    'Rain showers: Moderate': 'rain',
    'Rain showers: Violent': 'rain',
    'Snow showers slight': 'snow',
    'Snow showers heavy': 'snow',
    'Thunderstorm: Slight or moderate': 'storm',
    'Thunderstorm with slight hail': 'storm',
    'Thunderstorm with heavy hail': 'storm'
  };